language: java

jdk:
  - openjdk8

script:
  - mvn clean install cobertura:cobertura

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
notifications:
  email:
    on_failure: change
    on_success: change
